spnacceptstorageusr = This website uses local storage to improve user experience. Please refer to documentation to see what information is stored and sent over the wire. Our application is open source therefore our user can check what happens to his/her data.
btnacceptstorageusr = Accept Conditions
btncancel = Cancel
divtripscreatetripstopselmsg = Create trip stop selection mode active; Click on any marker to select a stop, or press Cancel to exit this screen
btntripsbrtripscreate = Create Trip
inptripsbrtripsfrom = Start typing...
inptripsbrtripsto = Start typing...
dlgtripsbrtripsfrom = From
dlgtripsbrtripsto = To
spnfavsroutesemptymsg = No Favorite routes to display
spnfavstripsemptymsg = No Favorite trips to display
spnfavserrreqmsg = Error when retrieving Favorite data from the server
spnfavsroutes = Routes
spnfavstrips = Custom Trips
spnfavsloginmsg = Please login using the More tab to enable Favorites
dlgtripsbrstoproutetm = Trip at&nbsp;
dlgtripsbrstoprouteselst = Start time
dlgtripsbrstoprouteseldu = Duration (shortest first)
dlgtripsbrstoprouteselem = Emptiness (most empty first)
dlgtripsbrstoproutesort = Sort by
tripsbrstoproutetitle = Trips from { $stopTitle } stop for route { $routeShortNm }
dlgtripsbrstoprouteerr = Unable to fetch the data for this bus stop combination. The server gave the following response: { $err }
more-reset = Reset and Clear Application
more-date-time-apps-dt-dev = Device
more-date-time-apps-dt-reg = Selected Region
more-date-time-apps-dt-cust = Custom
more-date-time-ttl = Application's Date/Time
dlg-trips-layers = Layers
btn-dlg-close = Close
trips-ttl = Trips
routes-ttl = Routes
favs-ttl = Favorites
more-ttl = More
more-region-ttl = Select Region
more-login = You are logged in as
more-login-anon = Anonymous
btn-more-signup = Sign Up
btn-more-signin = Sign In
btn-more-signout = Sign Out
btn-more-signrevoke = Revoke
btn-more-about = About
dlg-more-about-content-v = Version { $v } Build { $b }
dlg-more-about-content-cr = Copyright 2016-2017 Universitat Politecnica de Valencia. All rights reserved.
btn-more-new = What's New
dlg-more-hnew = Release News for Version
dlg-more-bnew1_0 = First Version
tblh-routes-sched-stop-names = Stop Names
tblh-routes-sched-arrival-times = Arrival Time
spn-routes-sched-err-req = Error getting the schedule for the selected route. Message from server:&nbsp;
spn-routes-err-req = Error loading routes for the selected region. Message from server:&nbsp;
div-loader-msg = Loading data...
btntripsmyloctp = My Current Location
btntripscreatetriptp = Create a Trip
btntripslayerstp = Show All Layers on the Map
btntripsbackcitytp = Back to Selected City
geolocationnotsupp = Geolocation is not supported by this browser.
geolocationerr = The Geolocation service failed with the following error: { $err }. If your location has been determined correctly, please ignore this message. Some browsers (like Firefox <51) are known to have bugs.
geolocationsuccmsg = Position (lat/lng): { $lat }/{ $lng }, accuracy of { $acc } meters
errloadingallmapstops = Error when trying to load all stops for the current region
