notify-e-trips-create-trip-err = Error al crear el viaje
notify-e-favs-add-fav-err = Error al agregar el favorito
notify-e-favs-rm-fav-err = No se ha podido eliminar el favorito
notify-i-trips-sentiment-analysis-non = Análisis de sentimiento no suportado por esta ciudad
notify-e-trips-sentiment-analysis-req-err = Error al cargamiento de la capa de análisis de sentimiento 
notify-i-trips-sentiment-analysis-non = Atasco trafico no soportado por esta ciudad
notify-e-trips-sentiment-analysis-req-err = Error al cargamiento de de la capa de atasco trafico
notify-e-app-unable-init-favs = No se puede inicializar la pestaña de favoritos. Vuelva a intentarlo más tarde o contáctenos.
notify-e-app-unable-init-maps-routes = No se pueden inicializar las pestañas de viajes y rutas. Vuelva a intentarlo más tarde o contáctenos.
notify-i-more-change-region-not-avail = La aplicación no se ha cargado aún, el cambio de región sigue estando deshabilitado
notify-w-routes-favs-not-add-rm = No se puede agregar o quitar favoritos
notify-w-trips-favs-not-load = Los favoritos aún no han terminado de cargar, espere hasta que se complete la carga.
notify-i-trips-fav-add-suc = Mejor recomendación viaje favorito añadido con éxito
notify-w-trips-fav-add-err = Error añadir mejor recomendación viaje a los favoritos
btn-trips-create-trip = Crear un viaje
btn-trips-sentiment-analysis = Mostrar Capa de Análisis Sentimiento
btn-trips-traffic-jam = Mostrar Capa de Atasco Traffico
btn-br-rfpw-trip-rec = Mostrar en el mapa
btn-br-rfpw-trip-rec-fav = Agregar a los favoritos
spnmorefeedbackerrreq = No se pueden recuperar los datos de Feedback.
btnroutesfav = Favorito
btnroutesshowonmap = Mostrar en Mapa
btnroutesschedule = Horario
btnmorehelp = Ayuda & Manual
dlgmorecontacttl = Contáctenos
btnmorecontact = Contáctenos
btnmorefeedback = Feedback
dlgmorefeedbackttl = Tu opinion importa
spnacceptstorageusr = Este sitio web utiliza el almacenamiento local para mejorar la experiencia del usuario. Consulte la documentación para ver qué información se almacena y envía a través del cable. Nuestra aplicación es de código abierto por lo tanto nuestro usuario puede comprobar lo que sucede a sus datos.
btnacceptstorageusr = Acepto condiciones
btncancel = Cancelar
btnsubmit = Enviar
divtripscreatetripstopselmsg = Modo de crear viajes está activo; Haga clic en cualquier marcador para seleccionar una parada o presione Cancelar para salir de esta pantalla
btntripsbrtripscreate = Crea Viaje
inptripsbrtripsfrom = Empieza a escribir...
inptripsbrtripsto = Empieza a escribir...
dlgtripsbrtripsfrom = De
dlgtripsbrtripsto = A
spnfavsroutesemptymsg = Ninguna ruta favorita
spnfavstripsemptymsg = Ningun viaje favorito
spnfavserrreqmsg = Error al recuperar Favoritos del servidor
spnfavsroutes = Rutas
spnfavstrips = Viajes
spnfavsloginmsg = Inicia sesión con la pestaña Más para habilitar los Favoritos
dlgtripsbrstoproutetm = Viaje a&nbsp;
dlgtripsbrstoprouteselst = Empieza a
dlgtripsbrstoprouteseldu = Duracion (primero mas corto)
dlgtripsbrstoprouteselem = Vacuidad (primero mas vacio)
dlgtripsbrstoproutesort = Ordenar por
tripsbrstoproutetitle = Viajes desde la parada { $stopTitle } para la ruta { $routeShortNm }
dlgtripsbrstoprouteerr = No se pueden obtener los datos de esta combinación de parada de autobús. El servidor dio la siguiente respuesta: { $err }
more-reset = Reiniciar y Limpiar Aplicación
more-date-time-apps-dt-dev = Dispozitivo
more-date-time-apps-dt-reg = Región Seleccionada
more-date-time-apps-dt-cust = Personalizado
more-date-time-ttl = Fecha/Hora de la Aplicación
dlg-trips-layers = Capas
btn-dlg-close = Cerrar
trips-ttl = Viajes
routes-ttl = Rutas
favs-ttl = Favoritos
more-ttl = Más
more-region-ttl = Seleccionar Region
more-login = Estás conectado como
more-login-anon = Anónimo
btn-more-signup = Registrar
btn-more-signin = Entrar
btn-more-signout = Salir
btn-more-signrevoke = Revocar
btn-more-about = Informacion
dlg-more-about-content-v = Versión { $v } Build { $b }
dlg-more-about-content-cr = Propriedad 2016-2017 Universitat Politecnica de Valencia. Todos los derechos reservados.
btn-more-new = Novedades
dlg-more-hnew = Noticias para la Versión
dlg-more-bnew1_0 = Primera Versión
tblh-routes-sched-stop-names = Nombres Paradas
tblh-routes-sched-arrival-times = Tiempo de llegada
spn-routes-sched-err-req = Error al obtener la programación de la ruta seleccionada. Mensaje del servidor:&nbsp;
spn-routes-err-req = Error al cargar rutas para la región seleccionada. Mensaje del servidor:&nbsp;
div-loader-msg = Cargar datos...
btn-trips-my-loc = Mi Ubicación Actual
btn-trips-layers = Mostrar todas las capas en el mapa
btn-trips-back-city = Volver a la ciudad seleccionada
geolocationnotsupp = La geolocalización no es suportada en este navegador.
geolocationerr = El servicio de Geolocalización falló con el siguiente error: {$err}. Si su ubicación se ha determinado correctamente, ignore este mensaje. Algunos navegadores (como Firefox <51) son conocidos por tener errores.
geolocationsuccmsg = Posición (lat / lng): {$lat} / {$lng}, exactitud de {$acc} metros
errloadingallmapstops = Error al intentar cargar todas las paradas para la región actual
msgtryagain = Compruebe la conexión y vuelva a intentarlo más tarde.