notify-e-trips-create-trip-err = Erro ao criar viagem
notify-i-trips-create-trip-non = Criar viagem não suportada para esta cidade
notify-e-favs-add-fav-err = Erro ao adicionar favoritos
notify-e-favs-rm-fav-err = Não é possível remover favorito
notify-i-trips-sentiment-analysis-non = Análise de sentimento não suportada para esta cidade
notify-e-trips-sentiment-analysis-req-err = Erro ao carregar a camada de análise de sentimento
notify-i-trips-sentiment-analysis-non = Engarrafamento não suportado para esta cidade
notify-e-trips-sentiment-analysis-req-err = Erro ao carregar a camada de engarrafamento
notify-e-app-unable-init-favs = Não foi possível inicializar a guia de favoritos. Tente novamente mais tarde ou contate-nos.
notify-e-app-unable-init-maps-routes = Não é possível inicializar as guias de viagens e rotas. Tente novamente mais tarde ou contate-nos.
notify-i-more-change-region-not-avail = A aplicação ainda não foi carregada, a mudança de região ainda está desativada
notify-w-routes-favs-not-add-rm = Não é possível adicionar ou remover favoritos
notify-w-trips-favs-not-load = Favoritos ainda não terminaram de carregar, aguarde até que o carregamento esteja completo
notify-i-trips-fav-add-suc = Melhor recomendada viagem favorita adicionada com sucesso
notify-w-trips-fav-add-err = Erro ao adicionar melhor recomendada viagem favorita
tblh-routes-sched-stop-names = Nome de Parada
tblh-routes-sched-arrival-times = Lista de Horas de Chegada
spn-routes-dlg-scheduling-ttl = Programação para rota 
spn-inp-routes-search-by-name = Toque / Clique para pesquisar rotas por nome curto e longo
btn-trips-create-trip = Criar uma viagem
btn-trips-sentiment-analysis = Mostrar Camada de Análise Sentimento 
btn-trips-traffic-jam = Mostrar Camada Atolamento
btn-br-rfpw-trip-rec = Mostrar no mapa
btn-br-rfpw-trip-rec-fav = Adicionar aos favoritos
spnmorefeedbackerrreq = Não é possível recuperar os dados de Feedback.
btnroutesfav = Favorito
btnroutesshowonmap = Mostrar no Mapa
btnroutesschedule = Horário
btnmorehelp = Ajuda & Manual
dlgmorecontacttl = Contate-Nos
btnmorecontact = Contate-Nos
btnmorefeedback = Comentários
dlgmorefeedbackttl = Sua opinião importa
spnacceptstorageusr = Este site usa armazenamento local para melhorar a experiência do usuário. Consulte a documentação para ver quais informações são armazenadas e enviadas por fio. Nosso aplicativo é de código aberto, portanto, nosso usuário pode verificar o que acontece com seus dados.
btnacceptstorageusr = Aceito Condições
btncancel = Cancelar
btnsubmit = Enviar
divtripscreatetripstopselmsg = Modo de criar viagems está ativo; Clique em qualquer marcador para selecionar uma parada ou pressione Cancelar para sair desta tela
btntripsbrtripscreate = Crie Viagem
inptripsbrtripsfrom = Começe a digitar...
inptripsbrtripsto = Começe a digitar...
dlgtripsbrtripsfrom = De
dlgtripsbrtripsto = A
spnfavsroutesemptymsg = Não há rotas favoritas
spnfavstripsemptymsg = Não há viagens favoritas
spnfavserrreqmsg = Erro ao recuperar Favoritos do servidor
spnfavsroutes = Rotas
spnfavstrips = Viagens
spnfavsloginmsg = Faça login usando a guia Mais para ativar os Favoritos
dlgtripsbrstoproutetm = Viagem&nbsp;
dlgtripsbrstoprouteselst = Hora de início
dlgtripsbrstoprouteseldu = Duração (mais curta primeiro)
dlgtripsbrstoprouteselem = Vazio (mais vazio primeiro)
dlgtripsbrstoproutesort = Ordenar por
tripsbrstoproutetitle = Viagens de paragem do { $stopTitle } para a rota { $routeShortNm }
dlgtripsbrstoprouteerr = Não é possível buscar os dados para esta combinação de parada de ônibus. O servidor deu a seguinte resposta: { $err }
more-reset = Redefinir e Limpar Aplicativo
more-date-time-apps-dt-dev = Dispozitivo
more-date-time-apps-dt-reg = Região Selecionada
more-date-time-apps-dt-cust = Personalizado
more-date-time-ttl = Data/Tempo de la Aplicação
dlg-trips-layers = Camadas
btn-dlg-close = Encerrar
trips-ttl = Viagens
routes-ttl = Rotas
favs-ttl = Favoritos
more-ttl = Mais
more-region-ttl = Escolha a Região
more-login = Estás logado como
more-login-anon = Anônimo
btn-more-signup = Inscrever-se
btn-more-signin = Assinar
btn-more-signout = Sair
btn-more-signrevoke = Revogar
btn-more-about = Sobre
dlg-more-about-content-v = Version { $v } Build { $b }
dlg-more-about-content-cr = Copyright 2016-2017 Universitat Politecnica de Valencia. All rights reserved.
btn-more-new = What's New
dlg-more-hnew = Notícias de lançamento por Version
dlg-more-bnew1_0 = Primeira versão
tblh-routes-sched-stop-names = Nomes de Paradas
tblh-routes-sched-arrival-times = Tempo de chegada
spn-routes-sched-err-req = Erro ao obter o cronograma da rota selecionada. Mensagem do servidor:&nbsp;
spn-routes-err-req = Erro ao carregar rotas para a região selecionada. Mensagem do servidor:&nbsp;
div-loader-msg = Carregando dados...
btn-trips-my-loc = Minha localização atual
btn-trips-layers = Mostrar todas as camadas no mapa
btn-trips-back-city = Voltar à Cidade Selecionada
geolocationnotsupp = A geolocalização não é suportada por este navegador.
geolocationerr = O serviço de Geolocalização falhou com o seguinte erro: { $err }. Se sua localização foi determinada corretamente, ignore esta mensagem. Alguns navegadores (como o Firefox <51) são conhecidos por terem erros.
geolocationsuccmsg = Posição (lat / lng): { $lat} / { $lng }, precisão de { $acc } metros
errloadingallmapstops = Erro ao tentar carregar todas as paradas para a região atual
msgtryagain = Verifique a conexão e tente novamente mais tarde.