spnacceptstorageusr = Este sitio web utiliza el almacenamiento local para mejorar la experiencia del usuario. Consulte la documentación para ver qué información se almacena y envía a través del cable. Nuestra aplicación es de código abierto por lo tanto nuestro usuario puede comprobar lo que sucede a sus datos.
btnacceptstorageusr = Acepto condiciones
btncancel = Cancelar
divtripscreatetripstopselmsg = Modo de crear viajes está activo; Haga clic en cualquier marcador para seleccionar una parada o presione Cancelar para salir de esta pantalla
btntripsbrtripscreate = Crea Viaje
inptripsbrtripsfrom = Empieza a escribir...
inptripsbrtripsto = Empieza a escribir...
dlgtripsbrtripsfrom = De
dlgtripsbrtripsto = A
spnfavsroutesemptymsg = Ninguna ruta favorita
spnfavstripsemptymsg = Ningun viaje favorito
spnfavserrreqmsg = Error al recuperar Favoritos del servidor
spnfavsroutes = Rutas
spnfavstrips = Viajes
spnfavsloginmsg = Inicia sesión con la pestaña Más para habilitar los Favoritos
dlgtripsbrstoproutetm = Viaje a&nbsp;
dlgtripsbrstoprouteselst = Empieza a
dlgtripsbrstoprouteseldu = Duracion (primero mas corto)
dlgtripsbrstoprouteselem = Vacuidad (primero mas vacio)
dlgtripsbrstoproutesort = Ordenar por
tripsbrstoproutetitle = Viajes desde la parada { $stopTitle } para la ruta { $routeShortNm }
dlgtripsbrstoprouteerr = No se pueden obtener los datos de esta combinación de parada de autobús. El servidor dio la siguiente respuesta: { $err }
more-reset = Reiniciar y Limpiar Aplicación
more-date-time-apps-dt-dev = Dispozitivo
more-date-time-apps-dt-reg = Región Seleccionada
more-date-time-apps-dt-cust = Personalizado
more-date-time-ttl = Fecha/Hora de la Aplicación
dlg-trips-layers = Capas
btn-dlg-close = Cerrar
trips-ttl = Viajes
routes-ttl = Rutas
favs-ttl = Favoritos
more-ttl = Más
more-region-ttl = Seleccionar Region
more-login = Estás conectado como
more-login-anon = Anónimo
btn-more-signup = Registrar
btn-more-signin = Entrar
btn-more-signout = Salir
btn-more-signrevoke = Revocar
btn-more-about = Informacion
dlg-more-about-content-v = Versión { $v } Build { $b }
dlg-more-about-content-cr = Propriedad 2016-2017 Universitat Politecnica de Valencia. Todos los derechos reservados.
btn-more-new = Novedades
dlg-more-hnew = Noticias para la Versión
dlg-more-bnew1_0 = Primera Versión
tblh-routes-sched-stop-names = Nombres Paradas
tblh-routes-sched-arrival-times = Tiempo de llegada
spn-routes-sched-err-req = Error al obtener la programación de la ruta seleccionada. Mensaje del servidor:&nbsp;
spn-routes-err-req = Error al cargar rutas para la región seleccionada. Mensaje del servidor:&nbsp;
div-loader-msg = Cargar datos...
btntripsmyloctp = Mi Ubicación Actual
btntripscreatetriptp = Crear un viaje
btntripslayerstp = Mostrar todas las capas en el mapa
btntripsbackcitytp = Volver a la ciudad seleccionada
geolocationnotsupp = La geolocalización no es suportada en este navegador.
geolocationerr = El servicio de Geolocalización falló con el siguiente error: {$err}. Si su ubicación se ha determinado correctamente, ignore este mensaje. Algunos navegadores (como Firefox <51) son conocidos por tener errores.
geolocationsuccmsg = Posición (lat / lng): {$lat} / {$lng}, exactitud de {$acc} metros
errloadingallmapstops = Error al intentar cargar todas las paradas para la región actual
