notify-e-trips-create-trip-err = Error creating trip
notify-e-favs-add-fav-err = Error adding favorite
notify-e-favs-rm-fav-err = Unable to remove favorite
notify-i-trips-sentiment-analysis-non = Sentiment analysis not supported for this city
notify-e-trips-sentiment-analysis-req-err = Error loading the sentiment analysis layer
notify-i-trips-traffic-jam-non = Traffic jam not supported for this city
notify-e-trips-traffic-jam-req-err = Error loading the traffic jam layer
notify-e-app-unable-init-favs = Unable to initialize the favorites tab. Try again later or contact us.
notify-e-app-unable-init-maps-routes = Unable to initialize the trips and routes tabs. Try again later or contact us.
notify-i-more-change-region-not-avail = The application has not loaded yet, region changing is still disabled
notify-w-routes-favs-not-add-rm = Unable to add or remove favorite
notify-w-trips-favs-not-load = Favorites have not finished loading yet, please wait until the loading is complete
notify-i-trips-fav-add-suc = Favorite best recommender trip successfully added
notify-w-trips-fav-add-err = Error adding favorite best recommender trip
btn-trips-create-trip = Create a Trip
btn-trips-sentiment-analysis = Show Sentiment Analysis Layer
btn-trips-traffic-jam = Show Traffic Jam Layer
btn-br-rfpw-trip-rec = Show on Map
btn-br-rfpw-trip-rec-fav = Add to Favorites
spnmorefeedbackerrreq = Unable to retrieve the feedback data. 
btnroutesfav = Favorite
btnroutesshowonmap = Show on Map
btnroutesschedule = Schedule
btnmorehelp = Help & Manual
dlgmorecontacttl = Contact us
btnmorecontact = Contact us
btnmorefeedback = Feedback
dlgmorefeedbackttl = Your opinion matters
spnacceptstorageusr = This website uses local storage to improve user experience. Please refer to documentation to see what information is stored and sent over the wire. Our application is open source therefore our user can check what happens to his/her data.
btnacceptstorageusr = Accept Conditions
btncancel = Cancel
btnsubmit = Submit
divtripscreatetripstopselmsg = Create trip stop selection mode active; Click on any marker to select a stop, or press Cancel to exit this screen
btntripsbrtripscreate = Create Trip
inptripsbrtripsfrom = Start typing...
inptripsbrtripsto = Start typing...
dlgtripsbrtripsfrom = From
dlgtripsbrtripsto = To
spnfavsroutesemptymsg = No Favorite routes to display
spnfavstripsemptymsg = No Favorite trips to display
spnfavserrreqmsg = Error when retrieving Favorite data from the server
spnfavsroutes = Routes
spnfavstrips = Custom Trips
spnfavsloginmsg = Please login using the More tab to enable Favorites
dlgtripsbrstoproutetm = Trip at&nbsp;
dlgtripsbrstoprouteselst = Start time
dlgtripsbrstoprouteseldu = Duration (shortest first)
dlgtripsbrstoprouteselem = Emptiness (most empty first)
dlgtripsbrstoproutesort = Sort by
tripsbrstoproutetitle = Trips from { $stopTitle } stop for route { $routeShortNm }
dlgtripsbrstoprouteerr = Unable to fetch the data for this bus stop combination. The server gave the following response: { $err }
more-reset = Reset and Clear Application
more-date-time-apps-dt-dev = Device
more-date-time-apps-dt-reg = Selected Region
more-date-time-apps-dt-cust = Custom
more-date-time-ttl = Application's Date/Time
dlg-trips-layers = Layers
btn-dlg-close = Close
trips-ttl = Trips
routes-ttl = Routes
favs-ttl = Favorites
more-ttl = More
more-region-ttl = Select Region
more-login = You are logged in as
more-login-anon = Anonymous
btn-more-signup = Sign Up
btn-more-signin = Sign In
btn-more-signout = Sign Out
btn-more-signrevoke = Revoke
btn-more-about = About
dlg-more-about-content-v = Version { $v } Build { $b }
dlg-more-about-content-cr = Copyright 2016-2017 Universitat Politecnica de Valencia. All rights reserved.
btn-more-new = What's New
dlg-more-hnew = Release News for Version
dlg-more-bnew1_0 = First Version
tblh-routes-sched-stop-names = Stop Names
tblh-routes-sched-arrival-times = Arrival Time
spn-routes-sched-err-req = Error getting the schedule for the selected route. Message from server:&nbsp;
spn-routes-err-req = Error loading routes for the selected region. Message from server:&nbsp;
div-loader-msg = Loading data...
btn-trips-my-loc = My Current Location
btn-trips-layers = Show All Layers on the Map
btn-trips-back-city = Back to Selected City
geolocationnotsupp = Geolocation is not supported by this browser.
geolocationerr = The Geolocation service failed with the following error: { $err }. If your location has been determined correctly, please ignore this message. Some browsers (like Firefox <51) are known to have bugs.
geolocationsuccmsg = Position (lat/lng): { $lat }/{ $lng }, accuracy of { $acc } meters
errloadingallmapstops = Error when trying to load all stops for the current region
msgtryagain = Please check the connection and try again later.