spnacceptstorageusr = Este site usa armazenamento local para melhorar a experiência do usuário. Consulte a documentação para ver quais informações são armazenadas e enviadas por fio. Nosso aplicativo é de código aberto, portanto, nosso usuário pode verificar o que acontece com seus dados.
btnacceptstorageusr = Aceito Condições
btncancel = Cancelar
divtripscreatetripstopselmsg = Modo de criar viagems está ativo; Clique em qualquer marcador para selecionar uma parada ou pressione Cancelar para sair desta tela
btntripsbrtripscreate = Crie Viagem
inptripsbrtripsfrom = Começe a digitar...
inptripsbrtripsto = Começe a digitar...
dlgtripsbrtripsfrom = De
dlgtripsbrtripsto = A
spnfavsroutesemptymsg = Não há rotas favoritas
spnfavstripsemptymsg = Não há viagens favoritas
spnfavserrreqmsg = Erro ao recuperar Favoritos do servidor
spnfavsroutes = Rotas
spnfavstrips = Viagens
spnfavsloginmsg = Faça login usando a guia Mais para ativar os Favoritos
tripsbrstoproutetitle = Viagens de paragem do { $stopTitle } para a rota { $routeShortNm }
more-reset = Redefinir e Limpar Aplicativo
more-date-time-apps-dt-dev = Dispozitivo
more-date-time-apps-dt-reg = Região Selecionada
more-date-time-apps-dt-cust = Personalizado
more-date-time-ttl = Data/Tempo de la Aplicação
dlg-trips-layers = Camadas
btn-dlg-close = Encerrar
trips-ttl = Viagens
routes-ttl = Rotas
favs-ttl = Favoritos
more-ttl = Mais
more-region-ttl = Escolha a Região
more-login = Estás logado como
more-login-anon = Anônimo
more-login-btn = Faça o Login
